"""empty message

Revision ID: af0addf4c6f9
Revises: ffdc0a98111c
Create Date: 2021-07-17 10:45:31.464130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0addf4c6f9'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('share_code', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'share_code')
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###
